version: "3"

services:
  db:
    image: mysql:latest
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: ${APPNAME}-mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    expose:
      - 3306
      - 33060

  wordpress:
    image: wordpress:latest
    container_name: ${APPNAME}-wordpress
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80
      - 443
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

  nginx:
    image: nginx-base:latest
    container_name: ${APPNAME}-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "DOMAIN=${DOMAIN}"
      - "APPNAME=${APPNAME}"
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled/
      - ./nginx/certs:/etc/ssl/certs/
      - ./nginx/private:/etc/ssl/private/

volumes:
  db_data:
  wp_data:
